### ISSUE TITLE
Please update the plugin to the new version 1.12

### ISSUE THREAD

**Issue by seedie** [MinelinkNetwork/CombatTagPlus#115]
version 1.3.0 does not work at all.

**Comment by ProgrammerDan** [comment]
Should be resolved by https://github.com/MinelinkNetwork/CombatTagPlus/pull/114  -- let me know if anything is broken after you update

**Comment by seedie** [comment]
Thanks a lot for your work programmer Dan, please can you provide me a link to the .jar? I have no idea how to build my own one :(

**Comment by Techcable** [comment]
I think the build failed and it didn't show up since I was using a broken version of craftbukkit.
Let me fix that and push another commit to trigger a rebuild.

**Comment by Techcable** [comment]
Here's a temporary build until the CI starts working again: https://transfer.sh/gPT1G/CombatTagPlus.jar
