### ISSUE TITLE
Issue with BETA Builds and NPC spawning

### ISSUE THREAD

**Issue by MoeXIV** [MinelinkNetwork/CombatTagPlus#13]
When an NPC spawns on the new BETA build (Latest as of 14th of April), when you have NPCs enabled, when you logout, they despawn but leave the name in chat. At 1 point I had about 12 "MoeXIV"s online.

VERSION: 1.7 Spigot Protocol Hack

**Comment by Byteflux** [comment]
I can't reproduce this issue on my 1.7.10 Protocol Patch server. Gonna guess this is probably related to an external plugin. Try using random names, it might work better.

**Comment by MoeXIV** [comment]
http://prntscr.com/6tzui6

**Comment by Sudzzy** [comment]
Are you able to reproduce this with no other plugins than CombatTagPlus?

**Comment by MoeXIV** [comment]
Yes, I am.

**Comment by Byteflux** [comment]
Can you take us through the steps you did to cause this behavior? We need to be able to experience this bug ourselves or we can't begin to fix it.

**Comment by MoeXIV** [comment]
All I did was:
Step 1: Log out
Done.

I just logout, and they continue to show from the multiplayer menu as more players then they should (Taking up real slots), showing up when you tab fill names, etc. Every time I log in, and out another one stays there, and it's only for certain people as well. Only happens to me and a friend on my servers, and on my friend server it only happens to his 1 friend.

**Comment by Sudzzy** [comment]
Could you please state the version you are using, and the config?

**Comment by Byteflux** [comment]
Can't reproduce on a server with no plugins + default config (also tested with random names disabled)

**Comment by MoeXIV** [comment]
Protocol Hack? It keeps happening to me and a friend so I know it's not just me. When I get home I'll pastebin my config and we'll go from there.

**Comment by Byteflux** [comment]
Please try 1.2.0 or one of the latest dev builds. If you are still having this problem, open a new issue specifying your CB/Spigot version and a pastebin of your CombatTagPlus config. Thanks.
