### ISSUE TITLE
Tab issue

### ISSUE THREAD

**Issue by Lilmac12312** [MinelinkNetwork/CombatTagPlus#19]
There's an issue where it does this with the tab: http://prntscr.com/6v2y2e
No errors are displayed within console.

**Comment by Byteflux** [comment]
Does not look like a CombatTagPlus issue. Is that player logged in or are they a NPC?

**Comment by Lilmac12312** [comment]
It is an issue with this plugin, I can have the other owner of the server confirm this for me. It's a NPC but someones when the player logs back in the NPC get removed correctly the players rank is removed and they get set to the default rank

**Comment by Byteflux** [comment]
CombatTagPlus does not do anything with ranks. What do you mean by rank? If you are having issues with NPCs, use random names because using actual player names for your NPC is buggy with other plugins.

**Comment by Lilmac12312** [comment]
Yeah that must of been the problem then, I'll try using random names and see how that goes.

**Comment by Byteflux** [comment]
Please try 1.2.0 or one of the latest dev builds. If you are still having this problem, open a new issue specifying your CB/Spigot version and a pastebin of your CombatTagPlus config. Thanks.
