### ISSUE TITLE
Add a option for CombatTag for only the attacker!

### ISSUE THREAD

**Issue by BigDrewBurt** [MinelinkNetwork/CombatTagPlus#21]
I really love how this plugin works, but wish to have the attacker become combat tagged. This is the only reason I have chose not to use this on my server.

**Comment by Sudzzy** [comment]
This is an option: https://github.com/MinelinkNetwork/CombatTagPlus/commit/3a68051a9579d7dd93f3a985b5dc6ab11da16c74

It will be in one of the latest development builds, find them here: http://ci.minelink.net/job/CombatTagPlus/
