### ISSUE TITLE
Add BossBarAPI support

### ISSUE THREAD

**Issue by Byteflux** [MinelinkNetwork/CombatTagPlus#26]

**Comment by xXBarchticXx** [comment]
Any eta?

**Comment by Byteflux** [comment]
I just added it, along with ActionBarAPI support, but from testing with the latest BossBarAPI there seems to be some buggy behavior. Maybe this is not an issue in the previous version, unsure. Can you try the latest dev buld @ http://ci.minelink.net/job/CombatTagPlus ?

**Comment by xXBarchticXx** [comment]
Works perfect :D! the boss is invis and ill test some more. Can you add like bossbarannouncer implementation so the combat tag counter overrides the bossbarannouncer?

**Comment by xXBarchticXx** [comment]
Is that even possible?

**Comment by Byteflux** [comment]
It should already override any existing bar. If it's not then maybe BossBarAnnouncer is overriding CombatTagPlus?

**Comment by Byteflux** [comment]
Also, just updated with some minor changes, please test if you can: http://ci.minelink.net/job/CombatTagPlus/

**Comment by xXBarchticXx** [comment]
bossbarannouncer has animations so every tick it displays a message  I believe that is why it is overriding it when it creates "a new" bossbar technically. I believe you should add bossbarannouncer as a soft-depend and add a while statement if bossbarannouncer is announcing a "message" you can override it if a player is combat tagged :P. Hoped this helps. I am just a beginner at coding so please don't judge. IDK if it makes sense or not.

**Comment by xXBarchticXx** [comment]
I mean I could just use action bar for countdown and then bossbar for announcing but this would convenience a lot more people as I don't think it is that hard to do. Sorry if that was offensive I don't know a whole lot about coding.

**Comment by Byteflux** [comment]
I think that it should be BossBarAnnouncer's responsibility to do a hasBar() check and try its best to not override other bars, beacuse a combat tag is more important than an announcement. As I believe this to be a BossBarAnnouncer issue, I'm gonna go ahead and say this is working.

**Comment by xXBarchticXx** [comment]
Ok. :D I'll make sure to message him!

**Comment by xXBarchticXx** [comment]
I'll make sure to message him!

**Comment by xXBarchticXx** [comment]
Overall its not that buggy but the refresh times for the countdown are slow so sometimes the bar disappears and then reappears. Also the developer of the plugin said this word by word "Yeah I can add that method. Or even a way to override for a specific player."

**Comment by xXBarchticXx** [comment]
Also the developer of the plugin said this word by word "Yeah I can add that method. Or even a way to override for a specific player."
