### ISSUE TITLE
NPCs not being removed from tab list when despawned?

### ISSUE THREAD

**Issue by Byteflux** [MinelinkNetwork/CombatTagPlus#27]

**Comment by Agazed** [comment]
YES YOU ARE READING MY MIND WITH THESE BUGS

Much needed fix

**Comment by mxson** [comment]
Logging out in a nether portal usually replicates it pretty well. :P

**Comment by Agazed** [comment]
When is this going to be fixed? It causes errors with other plugins with they check for online players.

**Comment by Byteflux** [comment]
@Agazed When someone contributes a fix. My time is currently occupied doing more important things that I cannot look into this currently.

Fortunately this is an open source project, anyone is more than welcome to fix the issue, or it'll have to wait until I have the free time to look into this myself (no ETA).

When someone submits a working pull request, I will more than gladly pull it.

**Comment by Agazed** [comment]
Can you just hide the NPC with npc.hidePlayer() ?

**Comment by Byteflux** [comment]
This issue should be resolved in the latest dev build: http://ci.minelink.net/job/CombatTagPlus/
