### ISSUE TITLE
NPCs don't despawn

### ISSUE THREAD

**Issue by xXBarchticXx** [MinelinkNetwork/CombatTagPlus#31]
Please help, NPCs don't despawn. 

![2015-06-25_13 24 12](https://cloud.githubusercontent.com/assets/10205575/8364805/b79c45e0-1b3d-11e5-9dfa-d17e10dad706.png)

Here is my plugin list! WorldGuard, WorldEdit, WorldBorder, WildSkript, WhatIsIt, Votifier, Vault, TitleMotdAdvacned, Tab, Skript, SkQuery, SilkSpawners, SexyMotd, ResourcePackAPI, PvPStats(skript I made), ProtocolLib, PlayerVaults, PlayerHeads, PlaceholderAPI, Pl3xIcons, ObsidianDestroyer, NoChestPlus, MultiverseCore, mcMMO, LibsDisguises, LampControl, Koth, HolographicDisplays, GAListener, ForceResourcePack, ForceFields, floAuction, FeatherBoard, FBasics, Factions, Essentials(package), EnderChestPlus, CustomCrates CSGO, CoreProtect, CombatTagPlus, Clearlag, CheckNameHistory, ChatControl, Buycraft, BossBarAPI!

Sorry if I am bombarding you with these :(

**Comment by Sudzzy** [comment]
Is this the actual NPC not de-spawning or just their name in the player list?

**Comment by xXBarchticXx** [comment]
The name in the player list (throws errors on mvdw's plugins)

**Comment by Sudzzy** [comment]
https://github.com/MinelinkNetwork/CombatTagPlus/issues/27 here's the official bug post. I am still yet to reproduce this issue, what does the error come up with on mvdw's plugin? (Does this error only come up with CombatTagPlus installed?)

**Comment by xXBarchticXx** [comment]
I believe the message spams console due to the fact the npc is like a player and featherboard, and the others see it as a player and initialize a scoreboard for them but at the same time it can't so it keeps trying. I hope you know what I mean. I can send the full error later.

**Comment by Byteflux** [comment]
This issue should be resolved in the latest dev build: http://ci.minelink.net/job/CombatTagPlus/
