### ISSUE TITLE
PvP Loggers stay on tab

### ISSUE THREAD

**Issue by Agazed** [MinelinkNetwork/CombatTagPlus#33]
http://prntscr.com/7mersm

Can you make them disappear from the tab when they logout?

**Comment by Agazed** [comment]
This happens when always-spawn: false

**Comment by Agazed** [comment]
Not all the PvP loggers actually stay on the tab although. This one doesnt seem to disappear.

**Comment by roastnewt** [comment]
We have the same issue, and always-spawn: true.  Can't seem to isolate when it's happening.  It seems like it happens more often when someone lags out rather than disconnecting.  Let me know if I can provide any more information.

**Comment by drtshock** [comment]
Can confirm this as well :(

**Comment by Agazed** [comment]
Any ideas for a PR? The author is currently busy and I can't seem to figure this out @drtshock

**Comment by Byteflux** [comment]
This issue should be resolved in the latest dev build: http://ci.minelink.net/job/CombatTagPlus/
