### ISSUE TITLE
Adding Maven Repo to jenkins server

### ISSUE THREAD

**Issue by rourke750** [MinelinkNetwork/CombatTagPlus#34]
Would you guys be able to get the maven plugin for jenkins?  It would allow other plugins to easily add your plugin as a dependency without having to do weird jenkins tricks of their own.

**Comment by Sudzzy** [comment]
CombatTagPlus can be fetched from this repo - http://repo.minelink.net/content/repositories/public

**Comment by rourke750** [comment]
Ah thank you.
