### ISSUE TITLE
Glitching through forcefield

### ISSUE THREAD

**Issue by mxson** [MinelinkNetwork/CombatTagPlus#38]
https://gfycat.com/HeavenlyEachGrison
Gif explains it pretty well, the player breaks the glass while next to it and slides through. I'm running the latest version.

**Comment by Sudzzy** [comment]
This was an issue with PaperSpigot, a recent commit has fixed this. Please get the latest version and your problem should be fixed.

**Comment by DahFrozen** [comment]
I've been having this issue as well. I'll try and reproduce it after I upload the new PaperSpigot build to my server.

**Comment by DahFrozen** [comment]
The latest PaperSpigot build appears to have made it harder for players to glitch through. They can still glitch through the force field. But it's harder for them to.

**Comment by Sudzzy** [comment]
Are you able to upload some evidence of them being able to do so? I need a reproducible method for this.

**Comment by DahFrozen** [comment]
@Sudzzy Here is the video:
https://www.youtube.com/watch?v=m5ZVHv9N9-w&

**Comment by Byteflux** [comment]
Update to the CombatTagPlus latest dev build and it should be fine.

**Comment by DahFrozen** [comment]
Okay.
