### ISSUE TITLE
NPC Doesn't spawn, displays error in console.

### ISSUE THREAD

**Issue by dotapurex1** [MinelinkNetwork/CombatTagPlus#47]
06.10 01:14:49 [Server] INFO ... 11 more
06.10 01:14:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
06.10 01:14:49 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
06.10 01:14:49 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
06.10 01:14:49 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
06.10 01:14:49 [Server] INFO at net.minelink.ctplus.listener.NpcListener.spawnNpc(NpcListener.java:57) ~[?:?]
06.10 01:14:49 [Server] INFO at net.minelink.ctplus.NpcManager.spawn(NpcManager.java:32) ~[?:?]
06.10 01:14:49 [Server] INFO at net.minelink.ctplus.compat.v1_7_R4.NpcPlayerHelperImpl.spawn(NpcPlayerHelperImpl.java:53) ~[?:?]
06.10 01:14:49 [Server] INFO Caused by: java.lang.NoSuchFieldError: players
06.10 01:14:49 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:298) [spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:744) [spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:77) [spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:747) [spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerList.disconnect(PlayerList.java:358) [spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:501) [spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:516) [spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Krunchit-f795f27]
06.10 01:14:49 [Server] INFO org.bukkit.event.EventException
06.10 01:14:49 [Server] ERROR Could not pass event PlayerQuitEvent to CombatTagPlus v1.2.2-SNAPSHOT

**Comment by Byteflux** [comment]
This is an issue with whatever fork of Spigot you are using. We only support official Spigot builds and PaperSpigot.

Feel free to submit a PR that works with your fork and official Spigot + PaperSpigot versions.

**Comment by Agazed** [comment]
What spigot version are you using?

**Comment by Techcable** [comment]
Don't use freak spigot forks and don't use 1.7
