### ISSUE TITLE
IMPORTANT block all commands except /ct

### ISSUE THREAD

**Issue by justin2001** [MinelinkNetwork/CombatTagPlus#48]
This is very important feature for a lot of people. Can you make the blacklist commands can work as the whitelist commands.

E.g. 
# This config option will make all the blacklist commands works as whitelist command.

blacklist works as whitelist: true

This will block all commands except what commands that you whitelisted.
Please add this, thanks!

**Comment by justin2001** [comment]
Bump

**Comment by Techcable** [comment]
Fixed by 09ee9c372bcf1729ce881973917b84f4a0a55353
Just set command blacklist to '*', then whitelist the commands you want

**Comment by justin2001** [comment]
So is there an example for this?

**Comment by Techcable** [comment]
Its pretty simple. Just set your blacklist to '*' to blacklist everything, and whitelist to what you want..........
