### ISSUE TITLE
Bug with spamming commands

### ISSUE THREAD

**Issue by christiaanbruijnes** [MinelinkNetwork/CombatTagPlus#52]
Hello,

I've found a bug and players on my server are abusing it.

You can block commands with CombatTagPlus, whenever I spam one of those commands you get kicked for disconnect.spam but won't get caught for combatlogging.

If I remove the disconnect.spam kick with ChatControl, a different bug appears: If I spam again, the combat log just goes off.

**Comment by Sudzzy** [comment]
https://github.com/MinelinkNetwork/CombatTagPlus/blob/master/CombatTagPlus/src/main/resources/config.yml#L38 is this set to true? If so, change it to false.

**Comment by christiaanbruijnes** [comment]
Then I will get more trouble, as example on restarting my server (every player in combat gets killed), or if a staff kicks someone (they will get killed). So I don't think that is smart to do.

Thanks for helping me, I really hope there will be a solution.

**Comment by christiaanbruijnes** [comment]
Bump, please this is a really serious issue on my server.

**Comment by CheatSupport** [comment]
Confirmed, once combat tagged players can spam a command and be kicked for "disconnect.spam". Then they won't be killed by the plugin

**Comment by Techcable** [comment]
Fixed by 30251cb48482373a6b1078b1137a68719a34d283
If a player is kicked for disconnect.spam they will still be combat-logged
