### ISSUE TITLE
cant hurt NPC

### ISSUE THREAD

**Issue by kristiantomov** [MinelinkNetwork/CombatTagPlus#58]
when a players logs out you cant hurt the npc... there are no errors in the console

**Comment by Techcable** [comment]
Version?

**Comment by kristiantomov** [comment]
Latest - 1.2.1.

**Comment by Sudzzy** [comment]
Are you attempting to hurt the NPC while in a specific region? Can the NPC take any damage at all e.g. lava damage? Are the players receiving a message?

**Comment by kristiantomov** [comment]
Yes I am, the region doesnt matter. The NPC cant taky any type of damage.And no, no messages are showing.

**Comment by Sudzzy** [comment]
Could you try latest via CI? http://ci.minelink.net/job/CombatTagPlus/

**Comment by kristiantomov** [comment]
Still doesnt work ;/

**Comment by Sudzzy** [comment]
Could you try this on a vanilla server with just combattagplus installed?

**Comment by kristiantomov** [comment]
damn it.. its working now... oh god now I need to find which plugin is blocking it -.-
