### ISSUE TITLE
Issues with mob tagging

### ISSUE THREAD

**Issue by WildWeazel** [MinelinkNetwork/CombatTagPlus#60]
When mob tagging is enabled, attacking player is not defined for PvP tags. This seems to be due to the check here which should be checking for Creature (mobs only) rather than LivingEntity (includes Player):
https://github.com/MinelinkNetwork/CombatTagPlus/blob/master/CombatTagPlus/src/main/java/net/minelink/ctplus/listener/TagListener.java#L78
Also attacking a mob without taking damage, or receiving projectile damage from a mob, does not tag you.

**Comment by Maxetto** [comment]
Subscribing on this as I have this problem too.
