### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by christiaanbruijnes** [MinelinkNetwork/CombatTagPlus#61]
https://github.com/Sudzzy/CombatTagPlus/commit/88021bf4d8255689e65062d079c30fe8bb8a54c8

Can this please be implemented in the plugin? Sudzzy made this for me in a custom plugin, this means I can't use the updated version anymore.

I also got another bug, I can't be teleported out while in combat even when the configuration option about teleportation is disabled.

I have a duel plugin and I am trying to teleport people to spawn once their enemy died, but they can't be teleported since your plugin is blocking it.

**Comment by christiaanbruijnes** [comment]
Bump?! I can't teleport players away while in combat, even if I have that config on false.

**Comment by Techcable** [comment]
There, its available in [build 134](http://ci.minelink.net/job/CombatTagPlus/134/)
