### ISSUE TITLE
Playersql 

### ISSUE THREAD

**Issue by BamBam042** [MinelinkNetwork/CombatTagPlus#63]
Hello ,

I currently facing a concern of duplication with playersql , if a player disconnects battle it poussédait tomb , and when he reconnects it to its inventory as if nothing had happened

Could you help me with her ​​?
Sorry for my bad english , good day

**Comment by Byteflux** [comment]
PlayerSQL is not supported. CombatTagPlus requires that all player files are stored and read on disk, not SQL.
