### ISSUE TITLE
Magic Items dropped (InstantKill)

### ISSUE THREAD

**Issue by Blamo27** [MinelinkNetwork/CombatTagPlus#65]
The plugin Magic gives a wand to the player, which can be kept in the inventory even when the player dies. With that option -which we enabled-, the player is supposed to never lose his wand on death. But CombatTag forces those items to drop on the floor when someone disconnect while tagged, making them lose there wands when they are not supposed to. Do you think this issue can be fixed...?

Note : we're using the insta-kill, and we can't use the PVPlogger option.

**Comment by Byteflux** [comment]
The plugin that is responsible for this behavior should be fixed to support CombatTagPlus NPCs.

**Comment by Blamo27** [comment]
Again, we're not using the NPCs, we're using the insta-kill option.

**Comment by Byteflux** [comment]
Sounds like an event priority problem or similar issue then.

CombatTagPlus instantly kills players who log off in combat when the option is enabled and as far as I can tell it kills the player normally like any other plugin would.

Still sounds like an issue Magic plugin needs to resolve.
