### ISSUE TITLE
Players get out of combat tag too soon when using a blink spell

### ISSUE THREAD

**Issue by tara81** [MinelinkNetwork/CombatTagPlus#74]
Players can use blink (teleport spell using the teleport event) to instantly leave combattag. version 1.9 , this issue was not in 1.8.

**Comment by ProgrammerDan** [comment]
I have a fix for this. I'm waiting on this PR to be merged: https://github.com/MinelinkNetwork/CombatTagPlus/pull/72

But if you're interested in fixing it locally, you can cherrypick this commit from my fork:
https://github.com/DevotedMC/CombatTagPlus/commit/be725504d3fcc8bc2913971f1400adb723bbd765

**Comment by ProgrammerDan** [comment]
Also for that fix and more just use this repository (that I also contribute to and maintain with @Maxopoly) https://github.com/CivCraft/CombatTagPlus/

**Comment by tara81** [comment]
I'm sorry I am not a coder, can you link me to a jar file :D

**Comment by ProgrammerDan** [comment]
:D Here you go: http://build.civcraft.co:8080/job/CombatTagPlus-master/5/   

or direct link: http://build.civcraft.co:8080/job/CombatTagPlus-master/5/artifact/CombatTagPlus/target/CombatTagPlus.jar

**Comment by tara81** [comment]
okay is it for 1.9.4 still ? :] if not can u get me a 1.9.4 version ?

**Comment by ProgrammerDan** [comment]
Yep -- it has support for 1.7 through to 1.10, including 1.9 and 1.9.4 . You're good to go!

**Comment by ProgrammerDan** [comment]
Did want to mention, once you install this version on your server add this line to your CombatTagPlus config file:

`untag-on-plugin-teleport: false`

**Comment by tara81** [comment]
awesome dan thanks a lot ! Btw you look sideways ! haha just messin

**Comment by ProgrammerDan** [comment]
:D I was probably falling asleep in my chair outside when the picture was taken so maybe I am!

**Comment by tara81** [comment]
lol add me on skype if you like : tara.martin81 - Love having developer friends =))
