### ISSUE TITLE
Can't customize some messages.

### ISSUE THREAD

**Issue by CheatSupport** [MinelinkNetwork/CombatTagPlus#75]
Please make a full language configuration..

for example, I can't customize message:
"You are not in combat."

**Comment by Maxopoly** [comment]
Make a full list of the messages that can't be customized yet and I'll fix it

**Comment by CheatSupport** [comment]
Ok, so far there is only these:
"You are not in combat." - this is shown when using /ct
"20 seconds remaining on your combat timer." - shown when doing /ct whiles't in combat

**Comment by CheatSupport** [comment]
? @Maxopoly

**Comment by Maxopoly** [comment]
I added it here https://github.com/Civcraft/CombatTagPlus/commit/1359b062d7b7574e24773fb7745ae5911df814ff

Merging it in this repo would require some cherry picking and fixing conflicts that I'm not willing to do right now, you can either wait for someone else to do that or get a build (which also includes some other stuff, which can be disabled though) [here](http://build.civcraft.co/job/CombatTagPlus-master/lastSuccessfulBuild/artifact/CombatTagPlus/target/CombatTagPlus.jar)

**Comment by CheatSupport** [comment]
Thanks @Maxopoly, but what do you mean "get a build (which also includes some other stuff" - what does it include that's different to the normal one?

**Comment by Maxopoly** [comment]
Some stuff we added for our server like a setting to tag users when they login and some bug fixes of which I dont know whether they were ever merged here. I think all of the gameplay changing stuff is disabled by default though.

**Comment by CheatSupport** [comment]
Ok, going to try it out now :) Thanks @Maxopoly
