### ISSUE TITLE
Question with command blacklisting and fix color codes in messages.

### ISSUE THREAD

**Issue by christiaanbruijnes** [MinelinkNetwork/CombatTagPlus#82]
1) https://gyazo.com/3df3d9bb31eec1c6e16636a3d88f7917 (I need help with enabling my duel command)
2) https://gyazo.com/63ca2257ecbf34b3d81a657b64a49fd1 (Fix color codes in 'you are not in combat messages)

**Comment by christiaanbruijnes** [comment]
~~3) I still can't teleport players away while in combat.~~ (Duplicate of #67, go provide me info there instead of opening a new issue)

**Comment by Techcable** [comment]
Gist your config.yml

**Comment by christiaanbruijnes** [comment]
I gave you more information in the other issue (#67)

**Comment by Maxopoly** [comment]
2) was introduced by https://github.com/MinelinkNetwork/CombatTagPlus/pull/78
