### ISSUE TITLE
Two slashes

### ISSUE THREAD

**Issue by christiaanbruijnes** [MinelinkNetwork/CombatTagPlus#83]
The commands which are disabled are having two slashes.

**Comment by Techcable** [comment]
I don't understand what you mean?
Do you mean that all commands with two slashes are disabled?
What is the desired behavior?

**Comment by christiaanbruijnes** [comment]
The issue is really small.

https://gyazo.com/3df3d9bb31eec1c6e16636a3d88f7917

It is showing two slashes when it should only show 1, that's it.

**Comment by CheatSupport** [comment]
Can confirm

**Comment by Techcable** [comment]
Fixed by 2aa6ca1a235f92311d455fbf6ab8dcee350d370e
