### ISSUE TITLE
Blacklist Issue

### ISSUE THREAD

**Issue by bitit0** [MinelinkNetwork/CombatTagPlus#87]
I blacklisted all commands, and whitelisted only certain commands, like 'f enemy', 'f ally', etc. I only put certain faction commands, but it appears as whitelisting any faction command will whitelist the whole chain of commands. My players can now do commands such as '/f warp' in combat.

**Comment by Byteflux** [comment]
Use the latest dev build. This issue should've been fixed in 2ba2c033eef7be53ba9e52b1758c6931e3b9fe09.
