### ISSUE TITLE
command blockage

### ISSUE THREAD

**Issue by CheatSupport** [MinelinkNetwork/CombatTagPlus#97]
Hi.

I listed /wild on the blacklist of commands when in combat. But, I made it so all commands except commands on the whitelist are disabled. The command /wild is not on the whitelist, so how come players can still do this?

/Wild is from fbasics. Thanks!

**Comment by Techcable** [comment]
What's your config.json?

**Comment by CheatSupport** [comment]
http://pastebin.com/cmqrhr0a

**Comment by Techcable** [comment]
What version of the plugin are you using?

**Comment by CheatSupport** [comment]
latest

**Comment by CheatSupport** [comment]
@Techcable

**Comment by CheatSupport** [comment]
Please help :) @Byteflux @Techcable @rourke750 @ProgrammerDan @CraigEge

**Comment by CheatSupport** [comment]
?

**Comment by CheatSupport** [comment]
Please try to fix soon..
