### ISSUE TITLE
Request for API

### ISSUE THREAD

**Issue by lkoeninger** [MinelinkNetwork/CombatTagPlus#98]
Hey guys,

could you add a kind of API to your plugin that let other plugin developers request if a player is currently in combat? Would be a great extention :)

**Comment by Maxopoly** [comment]
https://github.com/MinelinkNetwork/CombatTagPlus/blob/master/CombatTagPlus/src/main/java/net/minelink/ctplus/TagManager.java#L123

**Comment by lkoeninger** [comment]
oh nice, thank you!!

**Comment by lkoeninger** [comment]
mh TagManager constructor is not public so it can not get instanciated without reflection and the isTagged method is not static. Maybe you can modify this a little bit in your next build ;)

**Comment by Techcable** [comment]
You have to aquire an existing instance of the object, via the plugin object:
````
CombatTagPlus plugin = (CombatTagPlus) Bukkit.getPluginManager().getPlugin("CombatTagPlus");
TagManager tagManager = plugin.getTagManager();
````
